import os
import sys
import transaction

from pyramid.paster import (
    get_appsettings,
    setup_logging,
    )

from pyramid.scripts.common import parse_vars

from ..models.meta import Base
from ..models import (
    get_engine,
    get_session_factory,
    get_tm_session,
    )
from ..models import Mode
from ..models import Band


def usage(argv):
    cmd = os.path.basename(argv[0])
    print('usage: %s <config_uri> [var=value]\n'
          '(example: "%s development.ini")' % (cmd, cmd))
    sys.exit(1)


def main(argv=sys.argv):
    if len(argv) < 2:
        usage(argv)
    config_uri = argv[1]
    options = parse_vars(argv[2:])
    setup_logging(config_uri)
    settings = get_appsettings(config_uri, options=options)

    engine = get_engine(settings)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    session_factory = get_session_factory(engine)

    with transaction.manager:
        dbsession = get_tm_session(session_factory, transaction.manager)

        dbsession.add(Mode(mode='AM', hide=False))
        dbsession.add(Mode(mode='ARDOP', hide=False))
        dbsession.add(Mode(mode='ATV', hide=False))
        dbsession.add(Mode(mode='CHIP', hide=True))
        dbsession.add(Mode(mode='CHIP128', hide=False))
        dbsession.add(Mode(mode='CHIP64', hide=False))
        dbsession.add(Mode(mode='CLO', hide=False))
        dbsession.add(Mode(mode='CONTESTI', hide=False))
        dbsession.add(Mode(mode='CW', hide=False))
        dbsession.add(Mode(mode='PCW', hide=True))
        dbsession.add(Mode(mode='DIGITALVOICE', hide=False))
        dbsession.add(Mode(mode='DOMINO', hide=True))
        dbsession.add(Mode(mode='DOMINOEX', hide=False))
        dbsession.add(Mode(mode='DOMINOF', hide=False))
        dbsession.add(Mode(mode='DSTAR', hide=False))
        dbsession.add(Mode(mode='FAX', hide=False))
        dbsession.add(Mode(mode='FM', hide=False))
        dbsession.add(Mode(mode='FSK441', hide=False))
        dbsession.add(Mode(mode='HELL', hide=False))
        dbsession.add(Mode(mode='FMHELL', hide=False))
        dbsession.add(Mode(mode='FSKHELL', hide=False))
        dbsession.add(Mode(mode='HELL80', hide=False))
        dbsession.add(Mode(mode='HFSK', hide=False))
        dbsession.add(Mode(mode='PSKHELL', hide=False))
        dbsession.add(Mode(mode='ISCAT', hide=False))
        dbsession.add(Mode(mode='ISCAT-A', hide=False))
        dbsession.add(Mode(mode='ISCAT-B', hide=False))
        dbsession.add(Mode(mode='JT4', hide=False))
        dbsession.add(Mode(mode='JT4A', hide=False))
        dbsession.add(Mode(mode='JT4B', hide=False))
        dbsession.add(Mode(mode='JT4C', hide=False))
        dbsession.add(Mode(mode='JT4D', hide=False))
        dbsession.add(Mode(mode='JT4E', hide=False))
        dbsession.add(Mode(mode='JT4F', hide=False))
        dbsession.add(Mode(mode='JT4G', hide=False))
        dbsession.add(Mode(mode='JT6M', hide=False))
        dbsession.add(Mode(mode='JT9', hide=False))
        dbsession.add(Mode(mode='JT9-1', hide=False))
        dbsession.add(Mode(mode='JT9-2', hide=False))
        dbsession.add(Mode(mode='JT9-5', hide=False))
        dbsession.add(Mode(mode='JT9-10', hide=False))
        dbsession.add(Mode(mode='JT9-30', hide=False))
        dbsession.add(Mode(mode='JT44', hide=False))
        dbsession.add(Mode(mode='JT65', hide=False))
        dbsession.add(Mode(mode='JT65A', hide=False))
        dbsession.add(Mode(mode='JT65B', hide=False))
        dbsession.add(Mode(mode='JT65B2', hide=False))
        dbsession.add(Mode(mode='JT65C', hide=False))
        dbsession.add(Mode(mode='JT65C2', hide=False))
        dbsession.add(Mode(mode='MFSK', hide=True))
        dbsession.add(Mode(mode='MFSK4', hide=False))
        dbsession.add(Mode(mode='MFSK8', hide=False))
        dbsession.add(Mode(mode='MFSK11', hide=False))
        dbsession.add(Mode(mode='MFSK16', hide=False))
        dbsession.add(Mode(mode='MFSK22', hide=False))
        dbsession.add(Mode(mode='MFSK31', hide=False))
        dbsession.add(Mode(mode='MFSK32', hide=False))
        dbsession.add(Mode(mode='MFSK64', hide=False))
        dbsession.add(Mode(mode='MFSK128', hide=False))
        dbsession.add(Mode(mode='MSK144', hide=False))
        dbsession.add(Mode(mode='MT63', hide=False))
        dbsession.add(Mode(mode='OLIVIA', hide=True))
        dbsession.add(Mode(mode='OLIVIA 4/125', hide=False))
        dbsession.add(Mode(mode='OLIVIA 4/250', hide=False))
        dbsession.add(Mode(mode='OLIVIA 8/250', hide=False))
        dbsession.add(Mode(mode='OLIVIA 8/500', hide=False))
        dbsession.add(Mode(mode='OLIVIA 16/500', hide=False))
        dbsession.add(Mode(mode='OLIVIA 16/1000', hide=False))
        dbsession.add(Mode(mode='OLIVIA 32/1000', hide=False))
        dbsession.add(Mode(mode='OPERA', hide=False))
        dbsession.add(Mode(mode='OPERA-BEACON', hide=False))
        dbsession.add(Mode(mode='OPERA-QSO', hide=False))
        dbsession.add(Mode(mode='PAC', hide=False))
        dbsession.add(Mode(mode='PAC2', hide=False))
        dbsession.add(Mode(mode='PAC3', hide=False))
        dbsession.add(Mode(mode='PAC4', hide=False))
        dbsession.add(Mode(mode='PAX', hide=False))
        dbsession.add(Mode(mode='PAX2', hide=False))
        dbsession.add(Mode(mode='PKT', hide=False))
        dbsession.add(Mode(mode='PSK', hide=True))
        dbsession.add(Mode(mode='FSK31', hide=False))
        dbsession.add(Mode(mode='PSK10', hide=False))
        dbsession.add(Mode(mode='PSK31', hide=False))
        dbsession.add(Mode(mode='PSK63', hide=False))
        dbsession.add(Mode(mode='PSK63F', hide=False))
        dbsession.add(Mode(mode='PSK125', hide=False))
        dbsession.add(Mode(mode='PSK250', hide=False))
        dbsession.add(Mode(mode='PSK500', hide=False))
        dbsession.add(Mode(mode='PSK1000', hide=False))
        dbsession.add(Mode(mode='PSKAM10', hide=False))
        dbsession.add(Mode(mode='PSKAM31', hide=False))
        dbsession.add(Mode(mode='PSKAM50', hide=False))
        dbsession.add(Mode(mode='PSKFEC31', hide=False))
        dbsession.add(Mode(mode='QPSK31', hide=False))
        dbsession.add(Mode(mode='QPSK63', hide=False))
        dbsession.add(Mode(mode='QPSK125', hide=False))
        dbsession.add(Mode(mode='QPSK250', hide=False))
        dbsession.add(Mode(mode='QPSK500', hide=False))
        dbsession.add(Mode(mode='SIM31', hide=False))
        dbsession.add(Mode(mode='PSK2K', hide=False))
        dbsession.add(Mode(mode='Q15', hide=False))
        dbsession.add(Mode(mode='QRA64', hide=False))
        dbsession.add(Mode(mode='QRA64A', hide=False))
        dbsession.add(Mode(mode='QRA64B', hide=False))
        dbsession.add(Mode(mode='QRA64C', hide=False))
        dbsession.add(Mode(mode='QRA64D', hide=False))
        dbsession.add(Mode(mode='QRA64E', hide=False))
        dbsession.add(Mode(mode='ROS', hide=False))
        dbsession.add(Mode(mode='ROS-EME', hide=False))
        dbsession.add(Mode(mode='ROS-HF', hide=False))
        dbsession.add(Mode(mode='ROS-MF', hide=False))
        dbsession.add(Mode(mode='RTTY', hide=False))
        dbsession.add(Mode(mode='ASCI', hide=True))
        dbsession.add(Mode(mode='RTTYM', hide=False))
        dbsession.add(Mode(mode='SSB', hide=True))
        dbsession.add(Mode(mode='LSB', hide=False))
        dbsession.add(Mode(mode='USB', hide=False))
        dbsession.add(Mode(mode='SSTV', hide=False))
        dbsession.add(Mode(mode='THOR', hide=False))
        dbsession.add(Mode(mode='THRB', hide=False))
        dbsession.add(Mode(mode='THRBX', hide=False))
        dbsession.add(Mode(mode='TOR', hide=False))
        dbsession.add(Mode(mode='AMTORFEC', hide=False))
        dbsession.add(Mode(mode='GTOR', hide=False))
        dbsession.add(Mode(mode='V4', hide=False))
        dbsession.add(Mode(mode='VOI', hide=False))
        dbsession.add(Mode(mode='WINMOR', hide=False))
        dbsession.add(Mode(mode='WSPR', hide=False))

        dbsession.add(Band(band='2190m', lowerfreq=0.136, upperfreq=0.137, hide=False))
        dbsession.add(Band(band='630m', lowerfreq=0.472, upperfreq=0.479, hide=False))
        dbsession.add(Band(band='560m', lowerfreq=0.501, upperfreq=0.504, hide=False))
        dbsession.add(Band(band='160m', lowerfreq=1.8, upperfreq=2.0, hide=False))
        dbsession.add(Band(band='80m', lowerfreq=3.5, upperfreq=4.0, hide=False))
        dbsession.add(Band(band='60m', lowerfreq=5.06, upperfreq=5.45, hide=False))
        dbsession.add(Band(band='40m', lowerfreq=7.0, upperfreq=7.3, hide=False))
        dbsession.add(Band(band='30m', lowerfreq=10.1, upperfreq=10.15, hide=False))
        dbsession.add(Band(band='20m', lowerfreq=14.0, upperfreq=14.35, hide=False))
        dbsession.add(Band(band='17m', lowerfreq=18.068, upperfreq=18.168, hide=False))
        dbsession.add(Band(band='15m', lowerfreq=21.0, upperfreq=21.45, hide=False))
        dbsession.add(Band(band='12m', lowerfreq=24.890, upperfreq=24.99, hide=False))
        dbsession.add(Band(band='10m', lowerfreq=28.0, upperfreq=29.7, hide=False))
        dbsession.add(Band(band='6m', lowerfreq=50, upperfreq=54, hide=False))
        dbsession.add(Band(band='4m', lowerfreq=70, upperfreq=71, hide=False))
        dbsession.add(Band(band='2m', lowerfreq=144, upperfreq=148, hide=False))
        dbsession.add(Band(band='1.25m', lowerfreq=222, upperfreq=225, hide=False))
        dbsession.add(Band(band='70cm', lowerfreq=420, upperfreq=450, hide=False))
        dbsession.add(Band(band='33cm', lowerfreq=902, upperfreq=928, hide=False))
        dbsession.add(Band(band='23cm', lowerfreq=1240, upperfreq=1300, hide=False))
        dbsession.add(Band(band='13cm', lowerfreq=2300, upperfreq=2450, hide=False))
        dbsession.add(Band(band='9cm', lowerfreq=3300, upperfreq=3500, hide=False))
        dbsession.add(Band(band='6cm', lowerfreq=5650, upperfreq=5925, hide=False))
        dbsession.add(Band(band='3cm', lowerfreq=10000, upperfreq=10500, hide=False))
        dbsession.add(Band(band='1.25cm', lowerfreq=24000, upperfreq=24250, hide=False))
        dbsession.add(Band(band='6mm', lowerfreq=47000, upperfreq=47200, hide=False))
        dbsession.add(Band(band='4mm', lowerfreq=75500, upperfreq=81000, hide=False))
        dbsession.add(Band(band='2.5mm', lowerfreq=119980, upperfreq=120020, hide=False))
        dbsession.add(Band(band='2mm', lowerfreq=142000, upperfreq=149000, hide=False))
        dbsession.add(Band(band='1mm', lowerfreq=241000, upperfreq=250000, hide=False))
